import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ToolBox from "@/components/ui/ToolBox";
import MenuBar from "@/components/shared/MenuBar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <>
        <MenuBar/>
      <ToolBox />
        {children}
        </>
      </body>
    </html>
  );
}
